/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUsersIndexRouteImport } from './routes/_layout/users/index'
import { Route as LayoutTranslationsIndexRouteImport } from './routes/_layout/translations/index'
import { Route as LayoutPagesIndexRouteImport } from './routes/_layout/pages/index'
import { Route as LayoutMediaIndexRouteImport } from './routes/_layout/media/index'
import { Route as LayoutLocalesIndexRouteImport } from './routes/_layout/locales/index'
import { Route as LayoutGroupsIndexRouteImport } from './routes/_layout/groups/index'
import { Route as LayoutAuditLogIndexRouteImport } from './routes/_layout/audit-log/index'
import { Route as LayoutTranslationsNamespaceRouteImport } from './routes/_layout/translations/$namespace'
import { Route as LayoutPagesPageIdRouteImport } from './routes/_layout/pages/$pageId'
import { Route as LayoutGroupsGroupIdRouteImport } from './routes/_layout/groups/$groupId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersIndexRoute = LayoutUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTranslationsIndexRoute = LayoutTranslationsIndexRouteImport.update({
  id: '/translations/',
  path: '/translations/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPagesIndexRoute = LayoutPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMediaIndexRoute = LayoutMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLocalesIndexRoute = LayoutLocalesIndexRouteImport.update({
  id: '/locales/',
  path: '/locales/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsIndexRoute = LayoutGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuditLogIndexRoute = LayoutAuditLogIndexRouteImport.update({
  id: '/audit-log/',
  path: '/audit-log/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTranslationsNamespaceRoute =
  LayoutTranslationsNamespaceRouteImport.update({
    id: '/translations/$namespace',
    path: '/translations/$namespace',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPagesPageIdRoute = LayoutPagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsGroupIdRoute = LayoutGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/groups/$groupId': typeof LayoutGroupsGroupIdRoute
  '/pages/$pageId': typeof LayoutPagesPageIdRoute
  '/translations/$namespace': typeof LayoutTranslationsNamespaceRoute
  '/audit-log/': typeof LayoutAuditLogIndexRoute
  '/groups/': typeof LayoutGroupsIndexRoute
  '/locales/': typeof LayoutLocalesIndexRoute
  '/media/': typeof LayoutMediaIndexRoute
  '/pages/': typeof LayoutPagesIndexRoute
  '/translations/': typeof LayoutTranslationsIndexRoute
  '/users/': typeof LayoutUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof LayoutIndexRoute
  '/groups/$groupId': typeof LayoutGroupsGroupIdRoute
  '/pages/$pageId': typeof LayoutPagesPageIdRoute
  '/translations/$namespace': typeof LayoutTranslationsNamespaceRoute
  '/audit-log': typeof LayoutAuditLogIndexRoute
  '/groups': typeof LayoutGroupsIndexRoute
  '/locales': typeof LayoutLocalesIndexRoute
  '/media': typeof LayoutMediaIndexRoute
  '/pages': typeof LayoutPagesIndexRoute
  '/translations': typeof LayoutTranslationsIndexRoute
  '/users': typeof LayoutUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/groups/$groupId': typeof LayoutGroupsGroupIdRoute
  '/_layout/pages/$pageId': typeof LayoutPagesPageIdRoute
  '/_layout/translations/$namespace': typeof LayoutTranslationsNamespaceRoute
  '/_layout/audit-log/': typeof LayoutAuditLogIndexRoute
  '/_layout/groups/': typeof LayoutGroupsIndexRoute
  '/_layout/locales/': typeof LayoutLocalesIndexRoute
  '/_layout/media/': typeof LayoutMediaIndexRoute
  '/_layout/pages/': typeof LayoutPagesIndexRoute
  '/_layout/translations/': typeof LayoutTranslationsIndexRoute
  '/_layout/users/': typeof LayoutUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/groups/$groupId'
    | '/pages/$pageId'
    | '/translations/$namespace'
    | '/audit-log/'
    | '/groups/'
    | '/locales/'
    | '/media/'
    | '/pages/'
    | '/translations/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/groups/$groupId'
    | '/pages/$pageId'
    | '/translations/$namespace'
    | '/audit-log'
    | '/groups'
    | '/locales'
    | '/media'
    | '/pages'
    | '/translations'
    | '/users'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/'
    | '/_layout/groups/$groupId'
    | '/_layout/pages/$pageId'
    | '/_layout/translations/$namespace'
    | '/_layout/audit-log/'
    | '/_layout/groups/'
    | '/_layout/locales/'
    | '/_layout/media/'
    | '/_layout/pages/'
    | '/_layout/translations/'
    | '/_layout/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/': {
      id: '/_layout/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof LayoutUsersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/translations/': {
      id: '/_layout/translations/'
      path: '/translations'
      fullPath: '/translations/'
      preLoaderRoute: typeof LayoutTranslationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pages/': {
      id: '/_layout/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof LayoutPagesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/media/': {
      id: '/_layout/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof LayoutMediaIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/locales/': {
      id: '/_layout/locales/'
      path: '/locales'
      fullPath: '/locales/'
      preLoaderRoute: typeof LayoutLocalesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups/': {
      id: '/_layout/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof LayoutGroupsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audit-log/': {
      id: '/_layout/audit-log/'
      path: '/audit-log'
      fullPath: '/audit-log/'
      preLoaderRoute: typeof LayoutAuditLogIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/translations/$namespace': {
      id: '/_layout/translations/$namespace'
      path: '/translations/$namespace'
      fullPath: '/translations/$namespace'
      preLoaderRoute: typeof LayoutTranslationsNamespaceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pages/$pageId': {
      id: '/_layout/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof LayoutPagesPageIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups/$groupId': {
      id: '/_layout/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof LayoutGroupsGroupIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutGroupsGroupIdRoute: typeof LayoutGroupsGroupIdRoute
  LayoutPagesPageIdRoute: typeof LayoutPagesPageIdRoute
  LayoutTranslationsNamespaceRoute: typeof LayoutTranslationsNamespaceRoute
  LayoutAuditLogIndexRoute: typeof LayoutAuditLogIndexRoute
  LayoutGroupsIndexRoute: typeof LayoutGroupsIndexRoute
  LayoutLocalesIndexRoute: typeof LayoutLocalesIndexRoute
  LayoutMediaIndexRoute: typeof LayoutMediaIndexRoute
  LayoutPagesIndexRoute: typeof LayoutPagesIndexRoute
  LayoutTranslationsIndexRoute: typeof LayoutTranslationsIndexRoute
  LayoutUsersIndexRoute: typeof LayoutUsersIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutGroupsGroupIdRoute: LayoutGroupsGroupIdRoute,
  LayoutPagesPageIdRoute: LayoutPagesPageIdRoute,
  LayoutTranslationsNamespaceRoute: LayoutTranslationsNamespaceRoute,
  LayoutAuditLogIndexRoute: LayoutAuditLogIndexRoute,
  LayoutGroupsIndexRoute: LayoutGroupsIndexRoute,
  LayoutLocalesIndexRoute: LayoutLocalesIndexRoute,
  LayoutMediaIndexRoute: LayoutMediaIndexRoute,
  LayoutPagesIndexRoute: LayoutPagesIndexRoute,
  LayoutTranslationsIndexRoute: LayoutTranslationsIndexRoute,
  LayoutUsersIndexRoute: LayoutUsersIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
